### ISSUE TITLE
license?

### ISSUE THREAD

**Issue by tieguy** [tominsam/reader-starred-download#1]
Silly thing, but I ended up using parts of this for a personal feed reading tool, and because I'm actually a lawyer, I figure I should ask :) what's the license on this? Would like to reference it in my own repo. Thanks.

**Comment by tominsam** [comment]
Oh cool. Thanks for telling me. I’m on vacation right now so I can’t fix
the license but consider it 2 clause BSD and I’ll fix it next time I have a
computer.

**Comment by tieguy** [comment]
Thanks!

**Comment by tominsam** [comment]
Fixed. Finally.
